spring:
  liquibase:
    change-log: db/changelog/changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/support-service
    username: postgres
    password: postgres

  cloud:
    openfeign:
      client:
        config:
          phone-check:
            url: https://cleaner.dadata.ru/api/v1

logging:
  level:
    io.umid.supportservice: debug
    sql: trace
    org.springframework:
      security: trace

jwt:
  access-token-key: "aaaa_aaaa_aaaa_aaaa_aaaa_aaaa_32"
  refresh-token-key: "bbbb_bbbb_bbbb16"
  access-token-ttl: 5m
  refresh-token-ttl: 1d