spring:
  liquibase:
    change-log: db/changelog/changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/support-service
    username: postgres
    password: postgres

logging:
  level:
    io.umid.supportservice: debug
    sql: trace